language: python
python:
  - "2.7"
  - "2.6"

install:
- sudo apt-get install netcat python-virtualenv -y
- virtualenv ../env
- source ../env/bin/activate
- pip install -r requirements.txt

before_script:

script:
- nosetests --rednose -v ldap_notify/tests
